version: '3'

services:
  mysqlsrv:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "test"
    ports:
      - "3306:3306"
    volumes:
      - /home/rapi/Compose-Data/MySql:/var/lib/mysql
    restart: unless-stopped
